### ISSUE TITLE
Build the About Page

### ISSUE THREAD

**Issue by Llang8** [Llang8/collaboration-example-cdn-99#1]

**Comment by Llang8** [comment]
Hey Chris, can you build out the About page for me?

**Comment by bordedelcielo** [comment]
Of course, it will be the best About page you have ever seen.

**Comment by bordedelcielo** [comment]
I built the about page. Can you take a look at it when you have a convenient opportunity? Thanks!

**Comment by Llang8** [comment]
Thank you
